# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculosVarios.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.radioButton_DC = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_DC.setGeometry(QtCore.QRect(410, 200, 191, 23))
        self.radioButton_DC.setAutoFillBackground(False)
        self.radioButton_DC.setObjectName("radioButton_DC")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_DC)
        self.radioButton_ACM = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_ACM.setGeometry(QtCore.QRect(410, 240, 191, 23))
        self.radioButton_ACM.setAutoFillBackground(False)
        self.radioButton_ACM.setObjectName("radioButton_ACM")
        self.buttonGroup.addButton(self.radioButton_ACM)
        self.radioButton_ACB = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_ACB.setGeometry(QtCore.QRect(410, 280, 191, 23))
        self.radioButton_ACB.setAutoFillBackground(False)
        self.radioButton_ACB.setObjectName("radioButton_ACB")
        self.buttonGroup.addButton(self.radioButton_ACB)
        self.radioButton_ACT = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_ACT.setGeometry(QtCore.QRect(410, 320, 191, 23))
        self.radioButton_ACT.setAutoFillBackground(False)
        self.radioButton_ACT.setObjectName("radioButton_ACT")
        self.buttonGroup.addButton(self.radioButton_ACT)
        self.radioButton_A_HP = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_A_HP.setGeometry(QtCore.QRect(40, 130, 271, 23))
        self.radioButton_A_HP.setObjectName("radioButton_A_HP")
        self.radioButton_A_KVA = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_A_KVA.setGeometry(QtCore.QRect(40, 230, 261, 23))
        self.radioButton_A_KVA.setObjectName("radioButton_A_KVA")
        self.radioButton_HP_IE = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_HP_IE.setGeometry(QtCore.QRect(40, 380, 261, 23))
        self.radioButton_HP_IE.setObjectName("radioButton_HP_IE")
        self.radioButton_KVA_IE = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_KVA_IE.setGeometry(QtCore.QRect(40, 330, 261, 23))
        self.radioButton_KVA_IE.setObjectName("radioButton_KVA_IE")
        self.radioButton_A_KW = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_A_KW.setGeometry(QtCore.QRect(40, 180, 281, 23))
        self.radioButton_A_KW.setObjectName("radioButton_A_KW")
        self.radioButton_KW_IE = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_KW_IE.setGeometry(QtCore.QRect(40, 280, 261, 23))
        self.radioButton_KW_IE.setObjectName("radioButton_KW_IE")
        self.radioButton_FP_IE = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_FP_IE.setGeometry(QtCore.QRect(40, 430, 271, 23))
        self.radioButton_FP_IE.setObjectName("radioButton_FP_IE")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 70, 261, 101))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 321, 21))
        self.label_2.setObjectName("label_2")
        self.pushButtonAtras = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAtras.setGeometry(QtCore.QRect(0, 520, 89, 25))
        self.pushButtonAtras.setMouseTracking(True)
        self.pushButtonAtras.setStyleSheet("#pushButtonAtras{\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"#pushButtonAtras:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.pushButtonAtras.setCheckable(False)
        self.pushButtonAtras.setAutoRepeat(False)
        self.pushButtonAtras.setAutoExclusive(False)
        self.pushButtonAtras.setObjectName("pushButtonAtras")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 191, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 510, 191, 41))
        self.pushButton.setIconSize(QtCore.QSize(16, 16))
        self.pushButton.setObjectName("pushButton")
        self.label_mensaje = QtWidgets.QLabel(self.centralwidget)
        self.label_mensaje.setGeometry(QtCore.QRect(190, 560, 381, 17))
        self.label_mensaje.setText("")
        self.label_mensaje.setObjectName("label_mensaje")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(360, 60, 20, 401))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(500, 480, 281, 81))
        self.label_4.setStyleSheet("background: #B5EFE4")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton_DC.setText(_translate("MainWindow", "DC"))
        self.radioButton_ACM.setText(_translate("MainWindow", "AC Monofasico"))
        self.radioButton_ACB.setText(_translate("MainWindow", "AC Bifasico"))
        self.radioButton_ACT.setText(_translate("MainWindow", "AC Trifasico"))
        self.radioButton_A_HP.setText(_translate("MainWindow", "Amperios conociendo HP"))
        self.radioButton_A_KVA.setText(_translate("MainWindow", "Amperios conociendo kVA"))
        self.radioButton_HP_IE.setText(_translate("MainWindow", "HP conociendo I y E"))
        self.radioButton_KVA_IE.setText(_translate("MainWindow", "kVA conociendo I y E"))
        self.radioButton_A_KW.setText(_translate("MainWindow", "Amperios conociendo KW"))
        self.radioButton_KW_IE.setText(_translate("MainWindow", "kW conociendo I y E"))
        self.radioButton_FP_IE.setText(_translate("MainWindow", "Factor de Potencia conociendo I y E"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Seleccione el tipo de </span></p><p><span style=\" font-size:12pt; font-weight:600;\">alimentacion </span></p><p><span style=\" font-size:12pt; font-weight:600;\">que usa su motor:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Seleccione segun lo que desea encontrar</span></p></body></html>"))
        self.pushButtonAtras.setText(_translate("MainWindow", "Atras"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">CALCULOS VARIOS</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Siguiente"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>Nota: Para circuitos Bifasicos a 3 hilos la </p><p>corriente en el conductor comun es 1.41 </p><p>veces mayor que los otros 2 conductores.</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
