# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cambioDePolaridad.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 221, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 290, 241, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 241, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 241, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 210, 251, 17))
        self.label_5.setObjectName("label_5")
        self.textEdit_DenCorAnt = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_DenCorAnt.setGeometry(QtCore.QRect(310, 120, 91, 31))
        self.textEdit_DenCorAnt.setTabChangesFocus(True)
        self.textEdit_DenCorAnt.setObjectName("textEdit_DenCorAnt")
        self.textEdit_2_FacBobAnt = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2_FacBobAnt.setGeometry(QtCore.QRect(310, 160, 91, 31))
        self.textEdit_2_FacBobAnt.setTabChangesFocus(True)
        self.textEdit_2_FacBobAnt.setObjectName("textEdit_2_FacBobAnt")
        self.textEdit_3_IndAntDie = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3_IndAntDie.setGeometry(QtCore.QRect(310, 200, 91, 31))
        self.textEdit_3_IndAntDie.setTabChangesFocus(True)
        self.textEdit_3_IndAntDie.setObjectName("textEdit_3_IndAntDie")
        self.textEdit_4_PotAnt = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4_PotAnt.setGeometry(QtCore.QRect(310, 240, 91, 31))
        self.textEdit_4_PotAnt.setTabChangesFocus(True)
        self.textEdit_4_PotAnt.setObjectName("textEdit_4_PotAnt")
        self.textEdit_5_DenCorNue = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5_DenCorNue.setGeometry(QtCore.QRect(310, 280, 91, 31))
        self.textEdit_5_DenCorNue.setTabChangesFocus(True)
        self.textEdit_5_DenCorNue.setObjectName("textEdit_5_DenCorNue")
        self.textEdit_6_FacBobNue = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6_FacBobNue.setGeometry(QtCore.QRect(310, 320, 91, 31))
        self.textEdit_6_FacBobNue.setTabChangesFocus(True)
        self.textEdit_6_FacBobNue.setObjectName("textEdit_6_FacBobNue")
        self.textEdit_7_IndNueDie = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_7_IndNueDie.setGeometry(QtCore.QRect(310, 360, 91, 31))
        self.textEdit_7_IndNueDie.setTabChangesFocus(True)
        self.textEdit_7_IndNueDie.setObjectName("textEdit_7_IndNueDie")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 250, 231, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 330, 261, 17))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 330, 261, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 370, 261, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 490, 151, 17))
        self.label_10.setObjectName("label_10")
        self.label_PotNue = QtWidgets.QLabel(self.centralwidget)
        self.label_PotNue.setGeometry(QtCore.QRect(250, 490, 111, 17))
        self.label_PotNue.setText("")
        self.label_PotNue.setObjectName("label_PotNue")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 410, 131, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButtonLimpiar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLimpiar.setGeometry(QtCore.QRect(30, 430, 71, 25))
        self.pushButtonLimpiar.setObjectName("pushButtonLimpiar")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(440, 20, 321, 461))
        self.label_11.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:1, stop:0.144279 rgba(236, 255, 255, 249), stop:0.199005 rgba(0, 0, 0, 255));")
        self.label_11.setScaledContents(False)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 510, 171, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButtonAtras = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAtras.setGeometry(QtCore.QRect(0, 530, 89, 25))
        self.pushButtonAtras.setMouseTracking(True)
        self.pushButtonAtras.setStyleSheet("#pushButtonAtras{\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"#pushButtonAtras:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.pushButtonAtras.setCheckable(False)
        self.pushButtonAtras.setAutoRepeat(False)
        self.pushButtonAtras.setAutoExclusive(False)
        self.pushButtonAtras.setObjectName("pushButtonAtras")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Cambio de Polaridad</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>Densidad de Corriente Nueva (J1\')</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Densidad de Corriente Antigua (J1)"))
        self.label_4.setText(_translate("MainWindow", "Factor de Bobinado Antiguo (KW)"))
        self.label_5.setText(_translate("MainWindow", "Induccion Antigua en el Diente (Bz)"))
        self.label_6.setText(_translate("MainWindow", "Potencia Antigua (HP)"))
        self.label_8.setText(_translate("MainWindow", "Factor de Bobinado Nuevo (KW\')"))
        self.label_9.setText(_translate("MainWindow", "Induccion Nueva en el Diente (Bz\')"))
        self.label_10.setText(_translate("MainWindow", "Potencia Nueva (HP):"))
        self.pushButton.setText(_translate("MainWindow", "Calcular"))
        self.pushButtonLimpiar.setText(_translate("MainWindow", "Limpiar"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>Estos calculos aplican cuando por algun motivo se cambia la velocidad del motor y se mantiene constante la tension, frecuencia y tipo de bobinado.</p><p>Seguir los siguientes pasos:</p><p><span style=\" font-weight:600;\">a)</span> Utilizando los metodos de dimensionamiento calcular la nueva potencia (boton calcular)</p><p><span style=\" font-weight:600;\">b)</span> Por el diseño antiguo del entrehierro se recomienda hacer este cambio cuando las RPM deseadas sean menores que las RPM ya establecidos RPM\'&lt; RPM </p><p><span style=\" font-weight:600;\">c) </span>Con esta nueva polaridad verificar los parametros magneticos especialmente en el diente y la corona</p><p><span style=\" font-weight:600;\">d)</span> Verificar la compatibilidad de las ranuras del estator(S1) y del rotor (S2) con la nueva polaridad</p><p>Si todos estos pasos se han cumplido proceder al calculo de los demas parametros que permitan la reparacion. Finalmente verificar la nueva potencia nominal.</p><p><br/></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Calcular parametros"))
        self.pushButtonAtras.setText(_translate("MainWindow", "Atras"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
