# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cambioDePolaridad_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonAtras = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAtras.setGeometry(QtCore.QRect(0, 500, 89, 25))
        self.pushButtonAtras.setMouseTracking(True)
        self.pushButtonAtras.setStyleSheet("#pushButtonAtras{\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"#pushButtonAtras:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.pushButtonAtras.setCheckable(False)
        self.pushButtonAtras.setAutoRepeat(False)
        self.pushButtonAtras.setAutoExclusive(False)
        self.pushButtonAtras.setObjectName("pushButtonAtras")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 100, 181, 17))
        self.label.setObjectName("label")
        self.textEdit_1_NumRan = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_1_NumRan.setGeometry(QtCore.QRect(230, 90, 121, 31))
        self.textEdit_1_NumRan.setTabChangesFocus(True)
        self.textEdit_1_NumRan.setObjectName("textEdit_1_NumRan")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 181, 17))
        self.label_2.setObjectName("label_2")
        self.textEdit_2_NumPol = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2_NumPol.setGeometry(QtCore.QRect(230, 130, 121, 31))
        self.textEdit_2_NumPol.setTabChangesFocus(True)
        self.textEdit_2_NumPol.setObjectName("textEdit_2_NumPol")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 280, 181, 17))
        self.label_3.setObjectName("label_3")
        self.textEdit_Y = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Y.setGeometry(QtCore.QRect(420, 270, 121, 31))
        self.textEdit_Y.setObjectName("textEdit_Y")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(230, 320, 181, 17))
        self.label_4.setObjectName("label_4")
        self.textEdit_Yc = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Yc.setGeometry(QtCore.QRect(420, 310, 121, 31))
        self.textEdit_Yc.setObjectName("textEdit_Yc")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(230, 360, 181, 17))
        self.label_5.setObjectName("label_5")
        self.textEdit_AngEle = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_AngEle.setGeometry(QtCore.QRect(420, 350, 121, 31))
        self.textEdit_AngEle.setObjectName("textEdit_AngEle")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(230, 400, 191, 17))
        self.label_6.setObjectName("label_6")
        self.textEdit_Kd = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Kd.setGeometry(QtCore.QRect(420, 390, 121, 31))
        self.textEdit_Kd.setObjectName("textEdit_Kd")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(230, 440, 181, 17))
        self.label_7.setObjectName("label_7")
        self.textEdit_Kp = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Kp.setGeometry(QtCore.QRect(420, 430, 121, 31))
        self.textEdit_Kp.setObjectName("textEdit_Kp")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(230, 480, 181, 17))
        self.label_8.setObjectName("label_8")
        self.textEdit_Kw = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Kw.setGeometry(QtCore.QRect(420, 470, 121, 31))
        self.textEdit_Kw.setObjectName("textEdit_Kw")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 180, 121, 51))
        self.pushButton.setStyleSheet("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.199005 rgba(177, 222, 158, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton.setObjectName("pushButton")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 10, 251, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(230, 250, 101, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(40, 60, 91, 21))
        self.label_11.setObjectName("label_11")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonAtras.setText(_translate("MainWindow", "Atras"))
        self.label.setText(_translate("MainWindow", "Numero de Ranuras"))
        self.label_2.setText(_translate("MainWindow", "Numero de Polos"))
        self.label_3.setText(_translate("MainWindow", "Paso (Y):"))
        self.label_4.setText(_translate("MainWindow", "Paso Completo (Yc):"))
        self.label_5.setText(_translate("MainWindow", "Angulo Electrico (α):"))
        self.label_6.setText(_translate("MainWindow", "Factor de Distribucion (Kd):"))
        self.label_7.setText(_translate("MainWindow", "Factor de Paso (Kp):"))
        self.label_8.setText(_translate("MainWindow", "Factor de Bobinado (KW):"))
        self.pushButton.setText(_translate("MainWindow", "Calcular"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Calculo de Parametros</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Resultados:</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Datos:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
