# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cambiarTenNom.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 50, 171, 17))
        self.label.setObjectName("label")
        self.text_VueRanAnt = QtWidgets.QTextEdit(self.centralwidget)
        self.text_VueRanAnt.setGeometry(QtCore.QRect(240, 40, 131, 31))
        self.text_VueRanAnt.setObjectName("text_VueRanAnt")
        self.text_CapAnt = QtWidgets.QTextEdit(self.centralwidget)
        self.text_CapAnt.setGeometry(QtCore.QRect(240, 200, 131, 31))
        self.text_CapAnt.setObjectName("text_CapAnt")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 210, 171, 17))
        self.label_2.setObjectName("label_2")
        self.text_TenRedAnt = QtWidgets.QTextEdit(self.centralwidget)
        self.text_TenRedAnt.setGeometry(QtCore.QRect(240, 80, 131, 31))
        self.text_TenRedAnt.setObjectName("text_TenRedAnt")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 171, 17))
        self.label_3.setObjectName("label_3")
        self.text_TenRedNue = QtWidgets.QTextEdit(self.centralwidget)
        self.text_TenRedNue.setGeometry(QtCore.QRect(240, 120, 131, 31))
        self.text_TenRedNue.setObjectName("text_TenRedNue")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 130, 171, 17))
        self.label_4.setObjectName("label_4")
        self.text_SecCobAnt = QtWidgets.QTextEdit(self.centralwidget)
        self.text_SecCobAnt.setGeometry(QtCore.QRect(240, 160, 131, 31))
        self.text_SecCobAnt.setObjectName("text_SecCobAnt")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 170, 181, 17))
        self.label_5.setObjectName("label_5")
        self.text_NumPriEsp = QtWidgets.QTextEdit(self.centralwidget)
        self.text_NumPriEsp.setGeometry(QtCore.QRect(240, 240, 131, 31))
        self.text_NumPriEsp.setObjectName("text_NumPriEsp")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 250, 201, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 370, 191, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 410, 191, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 450, 191, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 490, 191, 17))
        self.label_10.setObjectName("label_10")
        self.label_VueRanNue = QtWidgets.QLabel(self.centralwidget)
        self.label_VueRanNue.setGeometry(QtCore.QRect(240, 370, 101, 17))
        self.label_VueRanNue.setObjectName("label_VueRanNue")
        self.label_SecAlaNue = QtWidgets.QLabel(self.centralwidget)
        self.label_SecAlaNue.setGeometry(QtCore.QRect(240, 410, 101, 17))
        self.label_SecAlaNue.setObjectName("label_SecAlaNue")
        self.label_CapNue = QtWidgets.QLabel(self.centralwidget)
        self.label_CapNue.setGeometry(QtCore.QRect(240, 450, 101, 17))
        self.label_CapNue.setObjectName("label_CapNue")
        self.label_NumEspNue = QtWidgets.QLabel(self.centralwidget)
        self.label_NumEspNue.setGeometry(QtCore.QRect(240, 490, 101, 17))
        self.label_NumEspNue.setObjectName("label_NumEspNue")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(30, 10, 201, 31))
        self.label_11.setObjectName("label_11")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 290, 131, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 310, 71, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButtonAtras = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAtras.setGeometry(QtCore.QRect(0, 530, 89, 25))
        self.pushButtonAtras.setMouseTracking(True)
        self.pushButtonAtras.setStyleSheet("#pushButtonAtras{\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"#pushButtonAtras:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.pushButtonAtras.setCheckable(False)
        self.pushButtonAtras.setAutoRepeat(False)
        self.pushButtonAtras.setAutoExclusive(False)
        self.pushButtonAtras.setObjectName("pushButtonAtras")
        self.label_mensaje = QtWidgets.QLabel(self.centralwidget)
        self.label_mensaje.setGeometry(QtCore.QRect(380, 290, 381, 61))
        self.label_mensaje.setText("")
        self.label_mensaje.setObjectName("label_mensaje")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Vueltas Ranura Antigua"))
        self.label_2.setText(_translate("MainWindow", "Capacidad Antigua"))
        self.label_3.setText(_translate("MainWindow", "Tension Red Antigua"))
        self.label_4.setText(_translate("MainWindow", "Tension Red Nueva"))
        self.label_5.setText(_translate("MainWindow", "Seccion de Cobre Antiguo"))
        self.label_6.setText(_translate("MainWindow", "Numero Primitivo de Espiras"))
        self.label_7.setText(_translate("MainWindow", "Vueltas Ranura Nueva:"))
        self.label_8.setText(_translate("MainWindow", "Seccion del alambre Nueva:"))
        self.label_9.setText(_translate("MainWindow", "Capacidad Nueva:"))
        self.label_10.setText(_translate("MainWindow", "Numero de Espiras Nueva:"))
        self.label_VueRanNue.setText(_translate("MainWindow", "-"))
        self.label_SecAlaNue.setText(_translate("MainWindow", "-"))
        self.label_CapNue.setText(_translate("MainWindow", "-"))
        self.label_NumEspNue.setText(_translate("MainWindow", "-"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Ingrese los datos:</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Calcular"))
        self.pushButton_2.setText(_translate("MainWindow", "Limpiar"))
        self.pushButtonAtras.setText(_translate("MainWindow", "Atras"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
