# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cambioDeFrecuenciaM.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 371, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 221, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 221, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 221, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 270, 221, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(110, 500, 671, 71))
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("background-color: qlineargradient(spread:, x1:0, y1:0, x2:1, y2:1, stop:0.467662 rgba(80, 106, 145, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.199005 rgba(177, 222, 158, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_6.setScaledContents(True)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.pushButtonAtras = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAtras.setGeometry(QtCore.QRect(0, 520, 89, 25))
        self.pushButtonAtras.setMouseTracking(True)
        self.pushButtonAtras.setStyleSheet("#pushButtonAtras{\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"#pushButtonAtras:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.pushButtonAtras.setCheckable(False)
        self.pushButtonAtras.setAutoRepeat(False)
        self.pushButtonAtras.setAutoExclusive(False)
        self.pushButtonAtras.setObjectName("pushButtonAtras")
        self.label_PotNue = QtWidgets.QLabel(self.centralwidget)
        self.label_PotNue.setGeometry(QtCore.QRect(260, 370, 91, 17))
        self.label_PotNue.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_PotNue.setScaledContents(False)
        self.label_PotNue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_PotNue.setObjectName("label_PotNue")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 370, 211, 17))
        self.label_8.setObjectName("label_8")
        self.label_RanEstNue = QtWidgets.QLabel(self.centralwidget)
        self.label_RanEstNue.setGeometry(QtCore.QRect(260, 410, 91, 17))
        self.label_RanEstNue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RanEstNue.setObjectName("label_RanEstNue")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 410, 211, 17))
        self.label_10.setObjectName("label_10")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 300, 101, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButtonLimpiar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLimpiar.setGeometry(QtCore.QRect(30, 310, 89, 25))
        self.pushButtonLimpiar.setObjectName("pushButtonLimpiar")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(360, 370, 67, 17))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 220, 221, 17))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(30, 450, 201, 17))
        self.label_11.setObjectName("label_11")
        self.label_SecCobNue = QtWidgets.QLabel(self.centralwidget)
        self.label_SecCobNue.setGeometry(QtCore.QRect(260, 450, 91, 17))
        self.label_SecCobNue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_SecCobNue.setObjectName("label_SecCobNue")
        self.textPotAnt = QtWidgets.QTextEdit(self.centralwidget)
        self.textPotAnt.setGeometry(QtCore.QRect(260, 60, 101, 31))
        self.textPotAnt.setTabChangesFocus(True)
        self.textPotAnt.setUndoRedoEnabled(False)
        self.textPotAnt.setReadOnly(False)
        self.textPotAnt.setProperty("tabChangesFocus2", "")
        self.textPotAnt.setObjectName("textPotAnt")
        self.textFreAnt = QtWidgets.QTextEdit(self.centralwidget)
        self.textFreAnt.setGeometry(QtCore.QRect(260, 110, 101, 31))
        self.textFreAnt.setTabChangesFocus(True)
        self.textFreAnt.setUndoRedoEnabled(False)
        self.textFreAnt.setReadOnly(False)
        self.textFreAnt.setProperty("tabChangesFocus2", "")
        self.textFreAnt.setObjectName("textFreAnt")
        self.textSecCobAnt = QtWidgets.QTextEdit(self.centralwidget)
        self.textSecCobAnt.setGeometry(QtCore.QRect(260, 210, 101, 31))
        self.textSecCobAnt.setTabChangesFocus(True)
        self.textSecCobAnt.setObjectName("textSecCobAnt")
        self.textNueFre = QtWidgets.QTextEdit(self.centralwidget)
        self.textNueFre.setGeometry(QtCore.QRect(260, 260, 101, 31))
        self.textNueFre.setTabChangesFocus(True)
        self.textNueFre.setReadOnly(False)
        self.textNueFre.setProperty("tabChangesFocus2", "")
        self.textNueFre.setObjectName("textNueFre")
        self.textRanEstAnt = QtWidgets.QTextEdit(self.centralwidget)
        self.textRanEstAnt.setGeometry(QtCore.QRect(260, 160, 101, 31))
        self.textRanEstAnt.setTabChangesFocus(True)
        self.textRanEstAnt.setReadOnly(False)
        self.textRanEstAnt.setProperty("tabChangesFocus2", "")
        self.textRanEstAnt.setObjectName("textRanEstAnt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">CAMBIO DE FRECUENCIA MOTOR ELECTRICO</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Potencia en el eje antiguo (HP):"))
        self.label_3.setText(_translate("MainWindow", "Frecuencia red antigua (Hz):"))
        self.label_4.setText(_translate("MainWindow", "Ranuras estatoricas antigua(S1):"))
        self.label_5.setText(_translate("MainWindow", "Nueva Frecuencia (Hz):"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>Nota: Valido cuando la tension de red y el tipo de bobinado se mantiene constante. Es importante tener en cuenta que aumentar la frecuencia de la red eléctrica puede aumentar la velocidad del motor, pero también puede causar sobrecalentamiento y otros problemas en el motor si no se toman las medidas adecuadas. </p></body></html>"))
        self.pushButtonAtras.setText(_translate("MainWindow", "Atras"))
        self.label_PotNue.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "Potencia en el eje nuevo(Hp):"))
        self.label_RanEstNue.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "Ranuras estatoricas nuevas:"))
        self.pushButton.setText(_translate("MainWindow", "Calcular"))
        self.pushButtonLimpiar.setText(_translate("MainWindow", "Limpiar"))
        self.label_9.setText(_translate("MainWindow", "Seccion de cobre antigua:"))
        self.label_11.setText(_translate("MainWindow", "Seccion de cobre nueva:"))
        self.label_SecCobNue.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
