# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(409, 306)
        self.zzzbuttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.zzzbuttonBox.setGeometry(QtCore.QRect(210, 270, 181, 32))
        self.zzzbuttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.zzzbuttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.zzzbuttonBox.setObjectName("zzzbuttonBox")
        self.textEdit_Efi = QtWidgets.QTextEdit(Dialog)
        self.textEdit_Efi.setGeometry(QtCore.QRect(140, 60, 131, 31))
        self.textEdit_Efi.setTabChangesFocus(True)
        self.textEdit_Efi.setObjectName("textEdit_Efi")
        self.textEdit_HP = QtWidgets.QTextEdit(Dialog)
        self.textEdit_HP.setGeometry(QtCore.QRect(140, 110, 131, 31))
        self.textEdit_HP.setTabChangesFocus(True)
        self.textEdit_HP.setObjectName("textEdit_HP")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 101, 17))
        self.label_4.setObjectName("label_4")
        self.label_A = QtWidgets.QLabel(Dialog)
        self.label_A.setGeometry(QtCore.QRect(140, 170, 121, 21))
        self.label_A.setObjectName("label_A")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 101, 17))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(140, 200, 131, 41))
        self.pushButton.setStyleSheet("background: #73C6B6;")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 101, 17))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 101, 17))
        self.label_2.setObjectName("label_2")
        self.textEdit_E = QtWidgets.QTextEdit(Dialog)
        self.textEdit_E.setGeometry(QtCore.QRect(140, 10, 131, 31))
        self.textEdit_E.setTabChangesFocus(True)
        self.textEdit_E.setObjectName("textEdit_E")

        self.retranslateUi(Dialog)
        self.zzzbuttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.zzzbuttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Corriente (A):</p></body></html>"))
        self.label_A.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">-</span></p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Tension (E):</p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "Calcular"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">HP:</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Eficiencia (%):</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
