# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog26.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 318)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(70, 280, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.textEdit_E = QtWidgets.QTextEdit(Dialog)
        self.textEdit_E.setGeometry(QtCore.QRect(100, 20, 81, 31))
        self.textEdit_E.setTabChangesFocus(True)
        self.textEdit_E.setObjectName("textEdit_E")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(220, 160, 131, 41))
        self.pushButton.setStyleSheet("background: #73C6B6;")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(-20, 170, 101, 17))
        self.label_4.setObjectName("label_4")
        self.textEdit_efi = QtWidgets.QTextEdit(Dialog)
        self.textEdit_efi.setGeometry(QtCore.QRect(300, 20, 81, 31))
        self.textEdit_efi.setTabChangesFocus(True)
        self.textEdit_efi.setObjectName("textEdit_efi")
        self.label_HP = QtWidgets.QLabel(Dialog)
        self.label_HP.setGeometry(QtCore.QRect(90, 170, 121, 21))
        self.label_HP.setObjectName("label_HP")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 90, 91, 20))
        self.label_2.setObjectName("label_2")
        self.textEdit_I = QtWidgets.QTextEdit(Dialog)
        self.textEdit_I.setGeometry(QtCore.QRect(100, 80, 81, 31))
        self.textEdit_I.setTabChangesFocus(True)
        self.textEdit_I.setObjectName("textEdit_I")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 30, 81, 20))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(190, 30, 101, 17))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(190, 70, 101, 51))
        self.label_5.setObjectName("label_5")
        self.textEdit_PF = QtWidgets.QTextEdit(Dialog)
        self.textEdit_PF.setGeometry(QtCore.QRect(300, 80, 81, 31))
        self.textEdit_PF.setTabChangesFocus(True)
        self.textEdit_PF.setObjectName("textEdit_PF")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Calcular"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">HP :</p></body></html>"))
        self.label_HP.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">-</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Corriente (A):</p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Tension (E):</p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Eficiencia (%):</p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Factor de </p><p align=\"right\">Potencia :</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
