# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog32.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 130, 101, 17))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(20, 230, 131, 41))
        self.pushButton.setStyleSheet("background: #73C6B6;")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(60, 180, 101, 17))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 131, 21))
        self.label_3.setObjectName("label_3")
        self.label_A = QtWidgets.QLabel(Dialog)
        self.label_A.setGeometry(QtCore.QRect(170, 180, 121, 21))
        self.label_A.setObjectName("label_A")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 30, 101, 17))
        self.label.setObjectName("label")
        self.textEdit_E = QtWidgets.QTextEdit(Dialog)
        self.textEdit_E.setGeometry(QtCore.QRect(170, 20, 81, 31))
        self.textEdit_E.setTabChangesFocus(True)
        self.textEdit_E.setObjectName("textEdit_E")
        self.textEdit_PF = QtWidgets.QTextEdit(Dialog)
        self.textEdit_PF.setGeometry(QtCore.QRect(170, 70, 81, 31))
        self.textEdit_PF.setTabChangesFocus(True)
        self.textEdit_PF.setObjectName("textEdit_PF")
        self.textEdit_kW = QtWidgets.QTextEdit(Dialog)
        self.textEdit_kW.setGeometry(QtCore.QRect(170, 120, 81, 31))
        self.textEdit_kW.setTabChangesFocus(True)
        self.textEdit_kW.setObjectName("textEdit_kW")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Potencia (kW):</p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "Calcular"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Corriente (A):</p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Factor de Potencia :</p></body></html>"))
        self.label_A.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">-</span></p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Tension (E):</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
