# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pesoCobre.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 595)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 360, 91, 41))
        self.pushButton.setStyleSheet("background: #85C1E9;")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 110, 231, 17))
        self.label.setObjectName("label")
        self.textEdit_long = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_long.setGeometry(QtCore.QRect(300, 100, 91, 31))
        self.textEdit_long.setTabChangesFocus(True)
        self.textEdit_long.setObjectName("textEdit_long")
        self.textEdit_cpar = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_cpar.setGeometry(QtCore.QRect(300, 150, 91, 31))
        self.textEdit_cpar.setTabChangesFocus(True)
        self.textEdit_cpar.setObjectName("textEdit_cpar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 160, 231, 17))
        self.label_2.setObjectName("label_2")
        self.textEdit_nesp = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_nesp.setGeometry(QtCore.QRect(300, 250, 91, 31))
        self.textEdit_nesp.setTabChangesFocus(True)
        self.textEdit_nesp.setObjectName("textEdit_nesp")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 260, 231, 17))
        self.label_3.setObjectName("label_3")
        self.textEdit_nbob = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_nbob.setGeometry(QtCore.QRect(300, 200, 91, 31))
        self.textEdit_nbob.setTabChangesFocus(True)
        self.textEdit_nbob.setObjectName("textEdit_nbob")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 210, 231, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 440, 231, 17))
        self.label_5.setObjectName("label_5")
        self.label_peso = QtWidgets.QLabel(self.centralwidget)
        self.label_peso.setGeometry(QtCore.QRect(300, 440, 111, 21))
        self.label_peso.setObjectName("label_peso")
        self.pushButtonAtras = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAtras.setGeometry(QtCore.QRect(0, 520, 89, 25))
        self.pushButtonAtras.setMouseTracking(True)
        self.pushButtonAtras.setStyleSheet("#pushButtonAtras{\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"#pushButtonAtras:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.pushButtonAtras.setCheckable(False)
        self.pushButtonAtras.setAutoRepeat(False)
        self.pushButtonAtras.setAutoExclusive(False)
        self.pushButtonAtras.setObjectName("pushButtonAtras")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 40, 391, 31))
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 300, 231, 41))
        self.label_6.setObjectName("label_6")
        self.textEdit_diam = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_diam.setGeometry(QtCore.QRect(300, 300, 91, 31))
        self.textEdit_diam.setTabChangesFocus(True)
        self.textEdit_diam.setObjectName("textEdit_diam")
        self.pushButton_limpiar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_limpiar.setGeometry(QtCore.QRect(440, 100, 89, 25))
        self.pushButton_limpiar.setObjectName("pushButton_limpiar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Calcular"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Longitud media de la espira (m):</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Conductores en Paralelo:</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Numero de Espiras:</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Numero de Bobinas:</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Peso de Cobre (Kg):</p></body></html>"))
        self.label_peso.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">-</span></p></body></html>"))
        self.pushButtonAtras.setText(_translate("MainWindow", "Atras"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">PESO DE COBRE</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Diametro de cable (mm):</p></body></html>"))
        self.pushButton_limpiar.setText(_translate("MainWindow", "Limpiar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
