# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window6.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(40, 80, 171, 17))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 171, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 171, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 170, 181, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 200, 171, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 230, 171, 17))
        self.label_6.setObjectName("label_6")
        self.text_IN = QtWidgets.QTextEdit(self.centralwidget)
        self.text_IN.setGeometry(QtCore.QRect(210, 70, 81, 31))
        self.text_IN.setObjectName("text_IN")
        self.text_EN = QtWidgets.QTextEdit(self.centralwidget)
        self.text_EN.setGeometry(QtCore.QRect(210, 100, 81, 31))
        self.text_EN.setObjectName("text_EN")
        self.text_Phi = QtWidgets.QTextEdit(self.centralwidget)
        self.text_Phi.setGeometry(QtCore.QRect(210, 130, 81, 31))
        self.text_Phi.setObjectName("text_Phi")
        self.text_EF = QtWidgets.QTextEdit(self.centralwidget)
        self.text_EF.setGeometry(QtCore.QRect(210, 160, 81, 31))
        self.text_EF.setObjectName("text_EF")
        self.text_I = QtWidgets.QTextEdit(self.centralwidget)
        self.text_I.setGeometry(QtCore.QRect(210, 190, 81, 31))
        self.text_I.setObjectName("text_I")
        self.text_E = QtWidgets.QTextEdit(self.centralwidget)
        self.text_E.setGeometry(QtCore.QRect(210, 220, 81, 31))
        self.text_E.setStyleSheet("")
        self.text_E.setObjectName("text_E")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 16, 221, 31))
        self.label.setObjectName("label")
        self.pushButtonAtras = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAtras.setGeometry(QtCore.QRect(0, 530, 89, 25))
        self.pushButtonAtras.setMouseTracking(True)
        self.pushButtonAtras.setStyleSheet("#pushButtonAtras{\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"#pushButtonAtras:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.pushButtonAtras.setCheckable(False)
        self.pushButtonAtras.setAutoRepeat(False)
        self.pushButtonAtras.setAutoExclusive(False)
        self.pushButtonAtras.setObjectName("pushButtonAtras")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 350, 221, 71))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 280, 41, 31))
        self.label_8.setObjectName("label_8")
        self.label_HP = QtWidgets.QLabel(self.centralwidget)
        self.label_HP.setGeometry(QtCore.QRect(100, 280, 101, 31))
        self.label_HP.setObjectName("label_HP")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(50, 316, 41, 31))
        self.label_10.setObjectName("label_10")
        self.label_KW = QtWidgets.QLabel(self.centralwidget)
        self.label_KW.setGeometry(QtCore.QRect(100, 320, 101, 31))
        self.label_KW.setObjectName("label_KW")
        self.label_IntNom = QtWidgets.QLabel(self.centralwidget)
        self.label_IntNom.setGeometry(QtCore.QRect(290, 360, 151, 51))
        self.label_IntNom.setObjectName("label_IntNom")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 110, 151, 61))
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 190, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_mensaje = QtWidgets.QLabel(self.centralwidget)
        self.label_mensaje.setGeometry(QtCore.QRect(340, 60, 251, 17))
        self.label_mensaje.setStyleSheet("color: red;")
        self.label_mensaje.setText("")
        self.label_mensaje.setObjectName("label_mensaje")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_1.setText(_translate("MainWindow", "IN (Intensidad Nominal):"))
        self.label_2.setText(_translate("MainWindow", "EN (Tension Nominal)    :"))
        self.label_3.setText(_translate("MainWindow", "Phi (desfase)                     :"))
        self.label_4.setText(_translate("MainWindow", "EF (Tension de fase)       : "))
        self.label_5.setText(_translate("MainWindow", "I (Intensidad)                    :"))
        self.label_6.setText(_translate("MainWindow", "E (Tension)                        :"))
        self.label.setText(_translate("MainWindow", "Ingrese todos los datos:"))
        self.pushButtonAtras.setText(_translate("MainWindow", "Atras"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">INTENSIDAD NOMINAL:</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">HP :</span></p></body></html>"))
        self.label_HP.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">KW:</span></p></body></html>"))
        self.label_KW.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.label_IntNom.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Calcular"))
        self.pushButton_2.setText(_translate("MainWindow", "Limpiar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
